### ISSUE TITLE
Wafflonia seeds require friends divisible by four

### ISSUE THREAD

**Issue by Cyprex** [bafomdad/uniquecrops#11]
The in-game book claims wafflonia crops only grow in even numbers, yet the code requires an amount divisible by four.
https://github.com/bafomdad/uniquecrops/blob/master/com/bafomdad/uniquecrops/crops/Wafflonia.java#L61

Thanks for this great mod, I'm having a lot of fun and it really is unique!

**Comment by Cyprex** [comment]
Also, for what it's worth, while testing a 2x2 layout of wafflonia crops(4 total),  one grew to 14% But bonemeal and a mod growth accelerator(Growth Aura from Wizardry) seemed to have no effect, I tried a full stack of bonemeal.

**Comment by bafomdad** [comment]
the crops needing a number of friends divisible by 4 is intentional. It just didn't feel right just having 2 side by side. the seeds are relatively easy to make, and they can drop more than one seed when harvested. so going by this logic, you can have clumps of crops between 4 and 16 growing together in a rectangle. If you want to grow more than 16, it is best to put some space between your squares of waffle crops.

it should be noted that bonemealing may seem like it works, as in the effect is played, but if the requirements are not met or it isn't allowed, the bonemeals will not be effective.

**Comment by Cyprex** [comment]
Yes, I did meet the requirements though and didn't get any growth with a stack of bonemeal, but the crop grew naturally, which seemed odd to me.
Consider adjusting the book for the changed behaviour, if you want I can PR an edit.

**Comment by bafomdad** [comment]
noted, I'll make a small change in the book description to reflect that behavior

**Comment by Cyprex** [comment]
Closing this issue, as it's been resolved in fa4b456
