### ISSUE TITLE
Super Crops not working correctly?

### ISSUE THREAD

**Issue by roukles123456789** [bafomdad/uniquecrops#38]
Whenever I try to make one of the super crops (putting the correct ingredients into artisia seeds and right-clicking the middle with a wildwood staff) it makes the super crop but the middle immediately breaks like I right-clicked it for a normal recipe. Am I doing something wrong?

**Comment by xenon-difluoride** [comment]
you probably have another mod that enables right-click harvest and thats causing the problem (Pam's Harvestcraft, V-tweaks, and Quark do that, there are probably others I havent seen though)

**Comment by luke-bravenboer** [comment]
Incorrect title- real issue is user error, stemming from the right-click harvesting feature of another mod which interferes with the way Artisia crop crafting works.

I can confirm that super crops are indeed working as intended in 0.2.1:
![2021-01-07_11 54 28](https://user-images.githubusercontent.com/3400211/103828145-580b5980-50df-11eb-89dd-39f2dd214f13.png)
