### ISSUE TITLE
Curseforge shows Required Dependency of Curios API(Fabric) When your mods updated for Forge

### ISSUE THREAD

**Issue by ModernGamingWorld** [bafomdad/uniquecrops#49]
This is showing on the latest 1.16.5 update

![chrome_vFnEbbZUYu](https://user-images.githubusercontent.com/75923060/129982446-f9189d7b-de26-4237-8022-67e46049190d.png)

**Comment by bafomdad** [comment]
both patchouli and curios api are required dependencies because the mod will crash without them, let alone having the modded minecraft instance refuse to load any further if it detects that either is not installed.

optional dependencies (that were present in the forge 1.12.2 version) are on the out and out. it is a requirement now

**Comment by ModernGamingWorld** [comment]
Yes @bafomdad I know I was pointing out that the Curios API is saying Curios API (Fabric) and it should say Curios API (Forge)

**Comment by bafomdad** [comment]
ah, I completely blanked on reading that part.

sorry, this is fixed
